Bump syn from 2.0.119 to 3.0.2 (#267)
Bumps [syn](https://github.com/dtolnay/syn) from 2.0.119 to 3.0.2.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/dtolnay/syn/releases">syn's
releases</a>.</em></p>
<blockquote>
<h2>3.0.2</h2>
<ul>
<li>Add <a
href="https://docs.rs/syn/3/syn/struct.Error.html#method.new_range"><code>Error::new_range(start..end,
&quot;msg&quot;)</code></a> (<a
href="https://redirect.github.com/dtolnay/syn/issues/2068">#2068</a>, <a
href="https://redirect.github.com/dtolnay/syn/issues/2070">#2070</a>)</li>
<li>Add <a
href="https://docs.rs/syn/3/syn/buffer/struct.Cursor.html#method.prev_span"><code>Cursor::prev_span</code></a></li>
</ul>
<h2>3.0.1</h2>
<ul>
<li>Parse const traits (<a
href="https://redirect.github.com/dtolnay/syn/issues/2056">#2056</a>, <a
href="https://redirect.github.com/dtolnay/syn/issues/2057">#2057</a>, <a
href="https://redirect.github.com/dtolnay/syn/issues/2058">#2058</a>, <a
href="https://redirect.github.com/dtolnay/syn/issues/2063">#2063</a>, <a
href="https://redirect.github.com/dtolnay/syn/issues/2064">#2064</a>)</li>
<li>Parse unsafe binder types (<a
href="https://redirect.github.com/dtolnay/syn/issues/2065">#2065</a>)</li>
<li>Parse impl restrictions (<a
href="https://redirect.github.com/dtolnay/syn/issues/2066">#2066</a>)</li>
</ul>
<h2>3.0.0</h2>
<p>This release contains adjustments to the syntax tree to account for
ongoing Rust language development from the 3 years since syn 2.0.0 and
to anticipate some in-flight Rust language RFCs.</p>
<p>These include: default values in fields, pinned type sugar, raw
lifetimes, generator blocks and functions, unnamed enum variants,
attributes in tuple types and tuple patterns, named arguments in
parenthesized generic argument lists, lightweight clones, const traits,
const function pointers, mutability restricted fields, supertrait auto
implementation, final associated functions, trait implementability
restrictions, const blocks in path arguments, item-level const blocks,
return type notation, never patterns, function delegation, mutable
by-reference bindings, in-place initialization, field projections,
explicitly dyn-compatible traits, view types, file-level frontmatter,
generic const arguments, guard patterns, lazy type aliases, explicitly
safe foreign items, super let, unsafe fields, pattern types,
heterogeneous try-blocks, function contracts, async function trait
bounds, static closure coroutine syntax, unsafe binder types, move
expressions, for-await loops, and postfix keywords.</p>
<!-- raw HTML omitted -->
<!-- raw HTML omitted -->
<h1>Breaking changes</h1>
<h2>Modifiers</h2>
<p>To reserve more room for language evolution, there are 10 new
non-exhaustive structs in the syntax tree having the following
commonality:</p>
<ul>
<li>
<p>Name ending in <code>Modifiers</code>. {<code>BlockModifiers</code>,
<code>ClosureModifiers</code>, <code>ConstModifiers</code>,
<code>FieldModifiers</code>, <code>FnModifiers</code>,
<code>ImplModifiers</code>, <code>LocalModifiers</code>,
<code>TraitBoundModifiers</code>, <code>TraitModifiers</code>,
<code>TypeModifiers</code>}</p>
</li>
<li>
<p>Each implements <code>Default</code>. The default value is guaranteed
to comprise no tokens.</p>
</li>
<li>
<p>Non-exhaustive. Can only be instantiated by Syn's parser or by
creating and then mutating <code>▁▁Modifiers::default()</code>.</p>
</li>
<li>
<p>Does not implement <code>Parse</code>. When parsing, they are parsed
by the enclosing syntax tree node.</p>
</li>
<li>
<p>Does not implement <code>ToTokens</code>. In some cases the syntax
that these nodes might hold in the future is not necessarily contiguous
tokens.</p>
</li>
<li>
<p>Provides <code>.require_empty() -&gt; Result&lt;()&gt;</code> which
returns a meaningfully spanned error if the modifiers are different from
the empty default. This enables a caller to reject syntax it does not
recognize without knowing what that syntax may be.</p>
</li>
</ul>
<h2>Types</h2>
<ul>
<li>
<p><code>Type::BareFn</code> has been renamed to
<code>Type::FnPtr</code> to mirror the compiler's terminology. Together
with this, <code>BareVariadic</code> is renamed to
<code>FnPtrVariadic</code>.</p>
</li>
<li>
<p>The mutually exclusive <code>const_token</code> and
<code>mutability</code> fields of <code>Type::Ptr</code> have been
unified into an enum of type <code>PointerMutability</code>, which was
already previously used by <code>Expr::RawAddr</code>.</p>
</li>
<li>
<p>Every <code>Type</code> variant now holds attributes, which can
represent the attributes of element types inside a tuple type, or
attributes for a function return type.</p>
</li>
<li>
<p><code>BareFnArg</code> is renamed to <code>NamedArg</code> and is
used in <code>ParenthesizedGenericArguments</code>, in addition to the
existing use in <code>Type::FnPtr</code>.</p>
</li>
</ul>
<h2>Expressions</h2>
<ul>
<li>In <code>Expr::Closure</code>, the fields <code>or1_token</code> and
<code>or2_token</code> have been renamed to <code>inputs_begin</code>
and <code>inputs_end</code> to indicate the beginning and ending
<code>|</code> token of the closure inputs.</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/dtolnay/syn/commit/88ee7be2197e61d6e84f0bff38eb2fe57998a765"><code>88ee7be</code></a>
Release 3.0.2</li>
<li><a
href="https://github.com/dtolnay/syn/commit/587bc203a0e975e8261a65791203e8912edb1c42"><code>587bc20</code></a>
Merge pull request <a
href="https://redirect.github.com/dtolnay/syn/issues/2070">#2070</a>
from dtolnay/emptyrange</li>
<li><a
href="https://github.com/dtolnay/syn/commit/96801f717ed1ae7943182afe1fd4c5857c50428b"><code>96801f7</code></a>
Allow Error::new_range at empty cursor range</li>
<li><a
href="https://github.com/dtolnay/syn/commit/9dc16c94cf0468dc4e4b1f6011cfd4040246c06c"><code>9dc16c9</code></a>
Merge pull request <a
href="https://redirect.github.com/dtolnay/syn/issues/2069">#2069</a>
from dtolnay/prevspan</li>
<li><a
href="https://github.com/dtolnay/syn/commit/1db76b7ba3f4e16430e6b2c96f160c05160e056e"><code>1db76b7</code></a>
Align on using impl trait across all Error constructors</li>
<li><a
href="https://github.com/dtolnay/syn/commit/bfa1ebf336f5fae0a0a22a89aeb991e2cd96c65a"><code>bfa1ebf</code></a>
Make Cursor::prev_span public</li>
<li><a
href="https://github.com/dtolnay/syn/commit/c6ac5e57086963d9fe549ea1576d062f30b1ae32"><code>c6ac5e5</code></a>
Merge pull request <a
href="https://redirect.github.com/dtolnay/syn/issues/2068">#2068</a>
from dtolnay/newrange</li>
<li><a
href="https://github.com/dtolnay/syn/commit/143645404be46202362a576650f2e1f8d56ae086"><code>1436454</code></a>
Add Error::new_range constructor taking Range&lt;Cursor&gt;</li>
<li><a
href="https://github.com/dtolnay/syn/commit/123c1485eaa5cb6db1034711136a0d65b17e7f0a"><code>123c148</code></a>
Release 3.0.1</li>
<li><a
href="https://github.com/dtolnay/syn/commit/bc11dddf65ebc8a1398f5ad9d0e1a1b4e9a1e9cf"><code>bc11ddd</code></a>
Merge pull request <a
href="https://redirect.github.com/dtolnay/syn/issues/2067">#2067</a>
from dtolnay/fastpeek</li>
<li>Additional commits viewable in <a
href="https://github.com/dtolnay/syn/compare/2.0.119...3.0.2">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=syn&package-manager=cargo&previous-version=2.0.119&new-version=3.0.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>